### ISSUE TITLE
Examples: set examples/index.html as first page of dev server

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig-editor.js#16]
Could we set [examples/index.html](https://github.com/openwisp/netjsonconfig-editor.js/blob/master/examples/index.html) as the first page of the dev server (`npm run dev`)?

Also, what is [examples/index1.html](https://github.com/openwisp/netjsonconfig-editor.js/blob/master/examples/index1.html) about? I can't see anything useful when I try access it from the development server. If it's not useful anymore could you remove it?

**Comment by gastonche** [comment]
working on this right now!

**Comment by gastonche** [comment]
in the latest updates i have deleted index1.html

**Comment by nemesisdesign** [comment]
Oh right, sorry I didn't notice.
