### ISSUE TITLE
[UI] Allow to load a different JSON-Schema

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig-editor.js#3]
OpenWISP 2 supports multiple configuration backends, different backends have slightly different JSON-Schemas and in openwisp2 is possilbe to change the configuration backend while editing the configuration.

Therefore we should add a built-in way to reload a different JSON-schema and rebuild the UI, but while maintaining the current JSON content being edited.

**Comment by gastonche** [comment]
The latest push I have made to my PR has implemented this feature
I will hook it into the basic editor once i start with it. But it works fine already with the advanced editor.
