### ISSUE TITLE
[UI] Start with an empty configuration

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig-editor.js#4]
Starting the editor with an empty JSON (`{]`) is probably the best option to not overwhelm the user with too many options.

**Comment by gastonche** [comment]
I don't quite understand what you mean by an empty configuration. Currently, I have made it possible for the developer to instantiate the editor with json or leave it empty. there is also a method to change the json data in the editor as well as the schema
@nemesisdesign

**Comment by nemesisdesign** [comment]
An empty configuration is an empty NetJSON, which is just `{}`.

I think what you have done now is fine.
